apiVersion: v1
kind: Service
metadata:
  name: k8s-minikube-vs-cluster
spec:
  selector:
    app: k8s-minikube-vs-cluster
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30082
