apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-cluster
  labels:
    app: k8s-cluster
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-cluster
  template:
    metadata:
      labels:
        app: k8s-cluster
    spec:
      containers:
        - name: k8s-cluster
          image: khawlarouiss/k8s-minikube-vs-cluster:latest
          ports:
            - containerPort: 8082
          startupProbe:
            httpGet:
              path: /
              port: 8082
            failureThreshold: 30
            periodSeconds: 2
          readinessProbe:
            httpGet:
              path: /
              port: 8082
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
